services:
  - type: web
    name: ai-assessment-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: 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
        sync: false
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health